148 Search Page UI
OGJG-ZAMONG/ZAMONG_Frontend_V1 pull request #307
Opened 2021-11-29 15:17 UTC by kkyo4994

## 작업 내용

- [x] 검색 페이지 UI

2021-11-29 15:18 UTC, kkyo4994 commented
만들어놓고안올림완전깜빡함죄송...

2021-11-30 06:27 UTC, kkyo4994 commented on zamong/src/components/Search/style.ts
> +  color: #ffffff;
오키바로고침잠만유

2021-11-30 06:28 UTC, kkyo4994 commented on zamong/src/components/Search/style.ts
> +  color: #ffffff;
아바로고쳐드릴게유딱기다리세요

2021-11-30 06:55 UTC, jcho0216 requested changes
콘후릭트 고쳐주세요

2021-11-30 06:56 UTC, jcho0216 commented
걍 내가 고침

2021-11-30 06:56 UTC, merged